language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run lint
#  - npm run test

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    all_branches: true
#  - npm run codacy
# - npm run deploy