language: node_js
node_js:
  - "6"

cache:
  directories:
    - "node_modules"

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: tests
      node_js: "6"
      script: npm run codacy
    - stage: tests
      node_js: "7"
      script: npm run codacy
    - stage: tests
      node_js: "8"
      script: npm run codacy
    - stage: deploy
      node_js: "6"
      script: skip
      deploy:
        provider: script
        script: sh scripts/deploy.sh
        on:
          branche: master