language: node_js
node_js:
  - "6"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install

script:
  - npm run lint
  - npm run codacy

deploy:
  provider: script
  script: sh scripts/deploy.sh
  on:
    branche: master
# - npm run codacy
# - npm run deploy
#  script: sh $TRAVIS_BUILD/scripts/deploy.sh
