language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
    - src/node_modules

before_script:
  - cd src
  - npm install

script:
  - npm run lint

after_success:
  - npm install -g serverless
  - sls deploy 