service: microservice-notes

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: v1

functions:
  app:
    name: microservice-notes-${self:provider.stage}
    handler: handler.microservice
    description: Microservice to notes
    memorySize: 512
    timeout: 150
    events:
      - http:
          method: get
          path: notes
          cors: true
      - http:
          method: post
          path: notes
          cors: true
      - http:
          method: put
          path: notes
          cors: true
      - http:
          method: delete
          path: notes
          cors: true

custom:
  stage: "${opt:stage, self:provider.stage}"

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:custom.stage}